services:
  - type: web
    name: expense-tracker-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python mamange.py migrate
    startCommand: gunicorn core.wsgi:application -- bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: REDIS_URL
        value: redis://localhost:6379/0
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

database:
  - name: expense-tracker-db
    plan: free